/**
 * Supabase Database Types for CabbageSEO
 * Matches the production database schema
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Enums matching the database
export type BillingInterval = "monthly" | "yearly";
export type CMSType = "wordpress" | "webflow" | "shopify" | "ghost" | "custom";
export type ContentStatus = "idea" | "researching" | "writing" | "draft" | "review" | "approved" | "scheduled" | "published" | "updating";
export type IssueSeverity = "critical" | "warning" | "info";
export type IssueType = "missing_meta_title" | "missing_meta_description" | "duplicate_title" | "thin_content" | "broken_link" | "orphan_page" | "redirect_chain" | "slow_page" | "missing_h1" | "multiple_h1" | "missing_alt" | "missing_schema";
export type KeywordStatus = "discovered" | "analyzed" | "clustered" | "queued" | "writing" | "published";
export type Plan = "starter" | "pro" | "pro_plus";
export type Role = "owner" | "admin" | "editor" | "viewer";
export type SubscriptionStatus = "active" | "canceled" | "past_due" | "trialing" | "paused";
export type TaskStatus = "pending" | "queued" | "running" | "completed" | "failed" | "canceled";
export type TaskType = "research" | "cluster" | "write" | "optimize" | "publish" | "crawl" | "audit" | "refresh" | "link";
export type IntegrationStatus = "active" | "error" | "disconnected";
export type AIOIssueType = "aio_low_entity_density" | "aio_poor_answer_structure" | "aio_missing_faq" | "aio_missing_howto" | "aio_weak_quotability" | "aio_missing_definitions" | "aio_no_expert_attribution" | "aio_ambiguous_context" | "aio_stale_content";
export type AIOPlatform = "google_aio" | "chatgpt" | "perplexity" | "bing_copilot";

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          dodo_customer_id: string | null;
          dodo_subscription_id: string | null;
          dodo_product_id: string | null;
          plan: Plan;
          billing_interval: BillingInterval | null;
          subscription_status: SubscriptionStatus | null;
          trial_ends_at: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          autopilot_enabled: boolean;
          settings: Json;
          brand_voice: string | null;
          overage_settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          dodo_customer_id?: string | null;
          dodo_subscription_id?: string | null;
          dodo_product_id?: string | null;
          plan?: Plan;
          billing_interval?: BillingInterval | null;
          subscription_status?: SubscriptionStatus | null;
          trial_ends_at?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          autopilot_enabled?: boolean;
          settings?: Json;
          brand_voice?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          dodo_customer_id?: string | null;
          dodo_subscription_id?: string | null;
          dodo_product_id?: string | null;
          plan?: Plan;
          billing_interval?: BillingInterval | null;
          subscription_status?: SubscriptionStatus | null;
          trial_ends_at?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          autopilot_enabled?: boolean;
          settings?: Json;
          brand_voice?: string | null;
          overage_settings?: Json;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          password_hash: string | null;
          email_verified: boolean;
          name: string | null;
          avatar_url: string | null;
          role: Role;
          google_id: string | null;
          last_login_at: string | null;
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email: string;
          password_hash?: string | null;
          email_verified?: boolean;
          name?: string | null;
          avatar_url?: string | null;
          role?: Role;
          google_id?: string | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          email?: string;
          password_hash?: string | null;
          email_verified?: boolean;
          name?: string | null;
          avatar_url?: string | null;
          role?: Role;
          google_id?: string | null;
          last_login_at?: string | null;
          last_active_at?: string | null;
          updated_at?: string;
        };
      };
      sessions: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          user_agent: string | null;
          ip_address: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          user_agent?: string | null;
          ip_address?: string | null;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          token?: string;
          user_agent?: string | null;
          ip_address?: string | null;
          expires_at?: string;
        };
      };
      sites: {
        Row: {
          id: string;
          organization_id: string;
          domain: string;
          name: string;
          description: string | null;
          status: string;
          // Citation Intelligence metrics
          total_citations: number;
          citations_this_week: number;
          citations_last_week: number;
          last_checked_at: string | null;
          geo_score_avg: number | null;
          // CMS Integration
          cms_type: CMSType | null;
          cms_url: string | null;
          cms_credentials: Json | null;
          cms_connected: boolean;
          cms_last_sync: string | null;
          gsc_connected: boolean;
          gsc_property_url: string | null;
          gsc_credentials: Json | null;
          gsc_last_sync: string | null;
          last_crawl_at: string | null;
          last_crawl_pages_count: number | null;
          settings: Json;
          brand_voice: string | null;
          target_audience: string | null;
          main_topics: Json;
          autopilot_enabled: boolean;
          autopilot_settings: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          domain: string;
          name: string;
          description?: string | null;
          status?: string;
          total_citations?: number;
          citations_this_week?: number;
          citations_last_week?: number;
          last_checked_at?: string | null;
          geo_score_avg?: number | null;
          cms_type?: CMSType | null;
          cms_url?: string | null;
          cms_credentials?: Json | null;
          cms_connected?: boolean;
          cms_last_sync?: string | null;
          gsc_connected?: boolean;
          gsc_property_url?: string | null;
          gsc_credentials?: Json | null;
          gsc_last_sync?: string | null;
          last_crawl_at?: string | null;
          last_crawl_pages_count?: number | null;
          settings?: Json;
          brand_voice?: string | null;
          target_audience?: string | null;
          main_topics?: Json;
          autopilot_enabled?: boolean;
          autopilot_settings?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          domain?: string;
          name?: string;
          description?: string | null;
          status?: string;
          total_citations?: number;
          citations_this_week?: number;
          citations_last_week?: number;
          last_checked_at?: string | null;
          geo_score_avg?: number | null;
          cms_type?: CMSType | null;
          cms_url?: string | null;
          cms_credentials?: Json | null;
          cms_connected?: boolean;
          cms_last_sync?: string | null;
          gsc_connected?: boolean;
          gsc_property_url?: string | null;
          gsc_credentials?: Json | null;
          gsc_last_sync?: string | null;
          last_crawl_at?: string | null;
          last_crawl_pages_count?: number | null;
          settings?: Json;
          brand_voice?: string | null;
          target_audience?: string | null;
          main_topics?: Json;
          autopilot_enabled?: boolean;
          autopilot_settings?: Json;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      keyword_clusters: {
        Row: {
          id: string;
          site_id: string;
          name: string;
          description: string | null;
          pillar_keyword: string | null;
          total_volume: number;
          avg_difficulty: number | null;
          keyword_count: number;
          suggested_articles: number | null;
          published_articles: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          name: string;
          description?: string | null;
          pillar_keyword?: string | null;
          total_volume?: number;
          avg_difficulty?: number | null;
          keyword_count?: number;
          suggested_articles?: number | null;
          published_articles?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          pillar_keyword?: string | null;
          total_volume?: number;
          avg_difficulty?: number | null;
          keyword_count?: number;
          suggested_articles?: number | null;
          published_articles?: number;
          updated_at?: string;
        };
      };
      keywords: {
        Row: {
          id: string;
          site_id: string;
          cluster_id: string | null;
          keyword: string;
          volume: number | null;
          difficulty: number | null;
          cpc: number | null;
          intent: string | null;
          category: string | null;
          serp_features: Json;
          serp_last_fetched: string | null;
          current_position: number | null;
          previous_position: number | null;
          impressions: number | null;
          clicks: number | null;
          ctr: number | null;
          ranking_url: string | null;
          ranking_last_updated: string | null;
          status: KeywordStatus;
          priority: number;
          content_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          cluster_id?: string | null;
          keyword: string;
          volume?: number | null;
          difficulty?: number | null;
          cpc?: number | null;
          intent?: string | null;
          category?: string | null;
          serp_features?: Json;
          serp_last_fetched?: string | null;
          current_position?: number | null;
          previous_position?: number | null;
          impressions?: number | null;
          clicks?: number | null;
          ctr?: number | null;
          ranking_url?: string | null;
          ranking_last_updated?: string | null;
          status?: KeywordStatus;
          priority?: number;
          content_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          cluster_id?: string | null;
          keyword?: string;
          volume?: number | null;
          difficulty?: number | null;
          cpc?: number | null;
          intent?: string | null;
          category?: string | null;
          serp_features?: Json;
          serp_last_fetched?: string | null;
          current_position?: number | null;
          previous_position?: number | null;
          impressions?: number | null;
          clicks?: number | null;
          ctr?: number | null;
          ranking_url?: string | null;
          ranking_last_updated?: string | null;
          status?: KeywordStatus;
          priority?: number;
          content_id?: string | null;
          updated_at?: string;
        };
      };
      content: {
        Row: {
          id: string;
          site_id: string;
          keyword_id: string | null;
          cluster_id: string | null;
          title: string;
          slug: string | null;
          meta_title: string | null;
          meta_description: string | null;
          body: string | null;
          body_format: string;
          excerpt: string | null;
          outline: Json | null;
          table_of_contents: Json | null;
          schema_markup: Json | null;
          has_faq_schema: boolean;
          has_how_to_schema: boolean;
          has_article_schema: boolean;
          internal_links: Json;
          suggested_internal_links: Json;
          word_count: number | null;
          reading_time: number | null;
          seo_score: number | null;
          readability_score: number | null;
          keyword_density: number | null;
          featured_image: string | null;
          images: Json;
          status: ContentStatus;
          assigned_to: string | null;
          published_url: string | null;
          published_at: string | null;
          cms_post_id: string | null;
          scheduled_for: string | null;
          version: number;
          last_edited_by: string | null;
          ai_model: string | null;
          ai_prompt_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          keyword_id?: string | null;
          cluster_id?: string | null;
          title: string;
          slug?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          body?: string | null;
          body_format?: string;
          excerpt?: string | null;
          outline?: Json | null;
          table_of_contents?: Json | null;
          schema_markup?: Json | null;
          has_faq_schema?: boolean;
          has_how_to_schema?: boolean;
          has_article_schema?: boolean;
          internal_links?: Json;
          suggested_internal_links?: Json;
          word_count?: number | null;
          reading_time?: number | null;
          seo_score?: number | null;
          readability_score?: number | null;
          keyword_density?: number | null;
          featured_image?: string | null;
          images?: Json;
          status?: ContentStatus;
          assigned_to?: string | null;
          published_url?: string | null;
          published_at?: string | null;
          cms_post_id?: string | null;
          scheduled_for?: string | null;
          version?: number;
          last_edited_by?: string | null;
          ai_model?: string | null;
          ai_prompt_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          keyword_id?: string | null;
          cluster_id?: string | null;
          title?: string;
          slug?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          body?: string | null;
          body_format?: string;
          excerpt?: string | null;
          outline?: Json | null;
          table_of_contents?: Json | null;
          schema_markup?: Json | null;
          has_faq_schema?: boolean;
          has_how_to_schema?: boolean;
          has_article_schema?: boolean;
          internal_links?: Json;
          suggested_internal_links?: Json;
          word_count?: number | null;
          reading_time?: number | null;
          seo_score?: number | null;
          readability_score?: number | null;
          keyword_density?: number | null;
          featured_image?: string | null;
          images?: Json;
          status?: ContentStatus;
          assigned_to?: string | null;
          published_url?: string | null;
          published_at?: string | null;
          cms_post_id?: string | null;
          scheduled_for?: string | null;
          version?: number;
          last_edited_by?: string | null;
          ai_model?: string | null;
          ai_prompt_version?: string | null;
          updated_at?: string;
        };
      };
      pages: {
        Row: {
          id: string;
          site_id: string;
          url: string;
          path: string;
          title: string | null;
          meta_description: string | null;
          h1: string | null;
          headings: Json | null;
          word_count: number | null;
          internal_links_out: Json;
          internal_links_in: number;
          external_links: Json;
          status_code: number | null;
          canonical_url: string | null;
          robots_directive: string | null;
          schema_types: Json;
          performance_score: number | null;
          lcp_ms: number | null;
          cls: number | null;
          is_indexed: boolean | null;
          indexed_at: string | null;
          content_type: string | null;
          content_id: string | null;
          last_crawled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          url: string;
          path: string;
          title?: string | null;
          meta_description?: string | null;
          h1?: string | null;
          headings?: Json | null;
          word_count?: number | null;
          internal_links_out?: Json;
          internal_links_in?: number;
          external_links?: Json;
          status_code?: number | null;
          canonical_url?: string | null;
          robots_directive?: string | null;
          schema_types?: Json;
          performance_score?: number | null;
          lcp_ms?: number | null;
          cls?: number | null;
          is_indexed?: boolean | null;
          indexed_at?: string | null;
          content_type?: string | null;
          content_id?: string | null;
          last_crawled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          url?: string;
          path?: string;
          title?: string | null;
          meta_description?: string | null;
          h1?: string | null;
          headings?: Json | null;
          word_count?: number | null;
          internal_links_out?: Json;
          internal_links_in?: number;
          external_links?: Json;
          status_code?: number | null;
          canonical_url?: string | null;
          robots_directive?: string | null;
          schema_types?: Json;
          performance_score?: number | null;
          lcp_ms?: number | null;
          cls?: number | null;
          is_indexed?: boolean | null;
          indexed_at?: string | null;
          content_type?: string | null;
          content_id?: string | null;
          last_crawled_at?: string | null;
          updated_at?: string;
        };
      };
      issues: {
        Row: {
          id: string;
          site_id: string;
          page_id: string | null;
          type: IssueType;
          severity: IssueSeverity;
          title: string;
          description: string | null;
          recommendation: string | null;
          affected_url: string | null;
          affected_element: string | null;
          current_value: string | null;
          suggested_value: string | null;
          is_resolved: boolean;
          resolved_at: string | null;
          resolved_by: string | null;
          can_auto_fix: boolean;
          auto_fix_applied: boolean;
          detected_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          page_id?: string | null;
          type: IssueType;
          severity: IssueSeverity;
          title: string;
          description?: string | null;
          recommendation?: string | null;
          affected_url?: string | null;
          affected_element?: string | null;
          current_value?: string | null;
          suggested_value?: string | null;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          can_auto_fix?: boolean;
          auto_fix_applied?: boolean;
          detected_at?: string;
          created_at?: string;
        };
        Update: {
          type?: IssueType;
          severity?: IssueSeverity;
          title?: string;
          description?: string | null;
          recommendation?: string | null;
          affected_url?: string | null;
          affected_element?: string | null;
          current_value?: string | null;
          suggested_value?: string | null;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          can_auto_fix?: boolean;
          auto_fix_applied?: boolean;
        };
      };
      tasks: {
        Row: {
          id: string;
          site_id: string;
          organization_id: string;
          type: TaskType;
          name: string;
          description: string | null;
          target_id: string | null;
          target_type: string | null;
          status: TaskStatus;
          priority: number;
          scheduled_for: string | null;
          started_at: string | null;
          completed_at: string | null;
          result: Json | null;
          error: string | null;
          attempts: number;
          max_attempts: number;
          last_attempt_at: string | null;
          triggered_by: string | null;
          triggered_by_user_id: string | null;
          is_autopilot: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          organization_id: string;
          type: TaskType;
          name: string;
          description?: string | null;
          target_id?: string | null;
          target_type?: string | null;
          status?: TaskStatus;
          priority?: number;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          result?: Json | null;
          error?: string | null;
          attempts?: number;
          max_attempts?: number;
          last_attempt_at?: string | null;
          triggered_by?: string | null;
          triggered_by_user_id?: string | null;
          is_autopilot?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          type?: TaskType;
          name?: string;
          description?: string | null;
          target_id?: string | null;
          target_type?: string | null;
          status?: TaskStatus;
          priority?: number;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          result?: Json | null;
          error?: string | null;
          attempts?: number;
          max_attempts?: number;
          last_attempt_at?: string | null;
          triggered_by?: string | null;
          triggered_by_user_id?: string | null;
          is_autopilot?: boolean;
          updated_at?: string;
        };
      };
      rankings: {
        Row: {
          id: string;
          site_id: string;
          keyword_id: string | null;
          content_id: string | null;
          keyword: string;
          url: string;
          position: number | null;
          impressions: number | null;
          clicks: number | null;
          ctr: number | null;
          date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          keyword_id?: string | null;
          content_id?: string | null;
          keyword: string;
          url: string;
          position?: number | null;
          impressions?: number | null;
          clicks?: number | null;
          ctr?: number | null;
          date: string;
          created_at?: string;
        };
        Update: {
          keyword?: string;
          url?: string;
          position?: number | null;
          impressions?: number | null;
          clicks?: number | null;
          ctr?: number | null;
          date?: string;
        };
      };
      usage_records: {
        Row: {
          id: string;
          organization_id: string;
          period_start: string;
          period_end: string;
          articles_generated: number;
          keywords_analyzed: number;
          serp_calls: number;
          pages_crawled: number;
          optimizations: number;
          articles_limit: number;
          keywords_limit: number;
          serp_calls_limit: number;
          crawl_pages_limit: number;
          on_demand_enabled: boolean;
          on_demand_spend_limit_cents: number;
          on_demand_spent_cents: number;
          overages_calculated: boolean;
          overages_amount_cents: number;
          overages_invoice_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          period_start: string;
          period_end: string;
          articles_generated?: number;
          keywords_analyzed?: number;
          serp_calls?: number;
          pages_crawled?: number;
          optimizations?: number;
          articles_limit: number;
          keywords_limit: number;
          serp_calls_limit: number;
          crawl_pages_limit: number;
          on_demand_enabled?: boolean;
          on_demand_spend_limit_cents?: number;
          on_demand_spent_cents?: number;
          overages_calculated?: boolean;
          overages_amount_cents?: number;
          overages_invoice_id?: string | null;
          created_at?: string;
        };
        Update: {
          articles_generated?: number;
          keywords_analyzed?: number;
          serp_calls?: number;
          pages_crawled?: number;
          optimizations?: number;
          on_demand_spent_cents?: number;
          overages_calculated?: boolean;
          overages_amount_cents?: number;
          overages_invoice_id?: string | null;
        };
      };
      usage_events: {
        Row: {
          id: string;
          organization_id: string;
          usage_record_id: string;
          event_type: string;
          quantity: number;
          internal_cost_cents: number;
          is_overage: boolean;
          resource_id: string | null;
          resource_type: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          usage_record_id: string;
          event_type: string;
          quantity?: number;
          internal_cost_cents: number;
          is_overage?: boolean;
          resource_id?: string | null;
          resource_type?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: never;
      };
      integrations: {
        Row: {
          id: string;
          organization_id: string;
          type: string;
          credentials: Json;
          status: IntegrationStatus;
          error: string | null;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          type: string;
          credentials: Json;
          status?: IntegrationStatus;
          error?: string | null;
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          type?: string;
          credentials?: Json;
          status?: IntegrationStatus;
          error?: string | null;
          last_synced_at?: string | null;
          updated_at?: string;
        };
      };
      audits: {
        Row: {
          id: string;
          site_id: string;
          type: string;
          overall_score: number | null;
          technical_score: number | null;
          content_score: number | null;
          aio_score: number | null;
          pages_scanned: number;
          issues_found: number;
          critical_issues: number;
          warning_issues: number;
          info_issues: number;
          duration_ms: number | null;
          status: string;
          error: string | null;
          results: Json;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          type?: string;
          overall_score?: number | null;
          technical_score?: number | null;
          content_score?: number | null;
          aio_score?: number | null;
          pages_scanned?: number;
          issues_found?: number;
          critical_issues?: number;
          warning_issues?: number;
          info_issues?: number;
          duration_ms?: number | null;
          status?: string;
          error?: string | null;
          results?: Json;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          overall_score?: number | null;
          technical_score?: number | null;
          content_score?: number | null;
          aio_score?: number | null;
          pages_scanned?: number;
          issues_found?: number;
          critical_issues?: number;
          warning_issues?: number;
          info_issues?: number;
          duration_ms?: number | null;
          status?: string;
          error?: string | null;
          results?: Json;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      credit_balance: {
        Row: {
          id: string;
          organization_id: string;
          prepaid_credits: number;
          bonus_credits: number;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          prepaid_credits?: number;
          bonus_credits?: number;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          prepaid_credits?: number;
          bonus_credits?: number;
          expires_at?: string | null;
          updated_at?: string;
        };
      };
      entities: {
        Row: {
          id: string;
          site_id: string;
          page_id: string | null;
          content_id: string | null;
          name: string;
          type: string | null;
          description: string | null;
          wikidata_id: string | null;
          wikipedia_url: string | null;
          mentions: number;
          context_quality: number | null;
          first_seen_at: string;
          last_seen_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          page_id?: string | null;
          content_id?: string | null;
          name: string;
          type?: string | null;
          description?: string | null;
          wikidata_id?: string | null;
          wikipedia_url?: string | null;
          mentions?: number;
          context_quality?: number | null;
          first_seen_at?: string;
          last_seen_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          type?: string | null;
          description?: string | null;
          wikidata_id?: string | null;
          wikipedia_url?: string | null;
          mentions?: number;
          context_quality?: number | null;
          last_seen_at?: string;
          updated_at?: string;
        };
      };
      citations: {
        Row: {
          id: string;
          site_id: string;
          page_id: string | null;
          platform: string;
          query: string;
          snippet: string | null;
          confidence: string;
          cited_at: string;
          last_verified_at: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          page_id?: string | null;
          platform: string;
          query: string;
          snippet?: string | null;
          confidence?: string;
          cited_at?: string;
          last_verified_at?: string | null;
        };
        Update: {
          snippet?: string | null;
          confidence?: string;
          last_verified_at?: string | null;
        };
      };
      geo_analyses: {
        Row: {
          id: string;
          site_id: string;
          organization_id: string;
          score: Json;
          tips: Json;
          queries: Json;
          opportunities: Json;
          raw_data: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          organization_id: string;
          score: Json;
          tips?: Json;
          queries?: Json;
          opportunities?: Json;
          raw_data?: Json;
          created_at?: string;
        };
        Update: {
          score?: Json;
          tips?: Json;
          queries?: Json;
          opportunities?: Json;
          raw_data?: Json;
        };
      };
      aio_analyses: {
        Row: {
          id: string;
          site_id: string;
          page_id: string;
          version: number;
          google_aio_score: number | null;
          chatgpt_score: number | null;
          perplexity_score: number | null;
          claude_score: number | null;
          gemini_score: number | null;
          combined_score: number | null;
          entity_density_score: number | null;
          quotability_score: number | null;
          answer_structure_score: number | null;
          schema_presence_score: number | null;
          freshness_score: number | null;
          authority_score: number | null;
          entities_found: Json;
          quotable_snippets: Json;
          missing_elements: Json;
          improvement_suggestions: Json;
          google_recommendations: Json;
          chatgpt_recommendations: Json;
          perplexity_recommendations: Json;
          model_used: string;
          tokens_used: number | null;
          analysis_duration_ms: number | null;
          analyzed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          page_id: string;
          version?: number;
          google_aio_score?: number | null;
          chatgpt_score?: number | null;
          perplexity_score?: number | null;
          claude_score?: number | null;
          gemini_score?: number | null;
          combined_score?: number | null;
          entity_density_score?: number | null;
          quotability_score?: number | null;
          answer_structure_score?: number | null;
          schema_presence_score?: number | null;
          freshness_score?: number | null;
          authority_score?: number | null;
          entities_found?: Json;
          quotable_snippets?: Json;
          missing_elements?: Json;
          improvement_suggestions?: Json;
          google_recommendations?: Json;
          chatgpt_recommendations?: Json;
          perplexity_recommendations?: Json;
          model_used?: string;
          tokens_used?: number | null;
          analysis_duration_ms?: number | null;
          analyzed_at?: string;
          created_at?: string;
        };
        Update: {
          google_aio_score?: number | null;
          chatgpt_score?: number | null;
          perplexity_score?: number | null;
          claude_score?: number | null;
          gemini_score?: number | null;
          combined_score?: number | null;
          entity_density_score?: number | null;
          quotability_score?: number | null;
          answer_structure_score?: number | null;
          schema_presence_score?: number | null;
          freshness_score?: number | null;
          authority_score?: number | null;
          entities_found?: Json;
          quotable_snippets?: Json;
          missing_elements?: Json;
          improvement_suggestions?: Json;
          google_recommendations?: Json;
          chatgpt_recommendations?: Json;
          perplexity_recommendations?: Json;
          tokens_used?: number | null;
          analysis_duration_ms?: number | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {
      billing_interval: BillingInterval;
      cms_type: CMSType;
      content_status: ContentStatus;
      issue_severity: IssueSeverity;
      issue_type: IssueType;
      keyword_status: KeywordStatus;
      plan: Plan;
      role: Role;
      subscription_status: SubscriptionStatus;
      task_status: TaskStatus;
      task_type: TaskType;
      integration_status: IntegrationStatus;
      aio_platform: AIOPlatform;
    };
  };
}

// Utility types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Insertable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type Updatable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
