import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Button variant="ghost" className="mb-8 text-zinc-400 hover:text-zinc-100" asChild>
          <Link href="/">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to home
          </Link>
        </Button>
        
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="space-y-6 text-zinc-400">
          <p className="text-zinc-300">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>
          
          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using CabbageSEO, you agree to be bound by these Terms of Service. 
              If you do not agree, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">2. Description of Service</h2>
            <p>
              CabbageSEO provides SEO and AI optimization tools including website analysis, 
              keyword research, content generation, and publishing capabilities. 
              We integrate with third-party services to deliver these features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">3. Your Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Provide accurate account information</li>
              <li>Only analyze websites you own or have permission to analyze</li>
              <li>Not use our service for spam, deceptive practices, or illegal activities</li>
              <li>Not attempt to reverse-engineer or exploit our systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">4. Content Ownership</h2>
            <p>
              You retain ownership of all content you create using CabbageSEO. 
              You grant us a license to store and process this content as needed to provide our services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">5. AI-Generated Content</h2>
            <p>
              Content generated by AI tools is provided as-is. You are responsible for reviewing 
              and editing AI-generated content before publishing. We do not guarantee the accuracy, 
              originality, or SEO performance of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">6. Billing</h2>
            <p>
              Paid plans are billed according to your selected plan. 
              Refunds are available within 14 days of purchase if you&apos;re not satisfied.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">7. Limitation of Liability</h2>
            <p>
              CabbageSEO is provided &quot;as is&quot; without warranties of any kind. 
              We are not liable for any damages arising from the use of our services, 
              including loss of data, revenue, or business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">8. Changes to Terms</h2>
            <p>
              We may update these terms at any time. Continued use of CabbageSEO after 
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-100 mb-3">9. Contact</h2>
            <p>
              Questions about these terms? Email us at arjun@cabbageseo.com or reach out on <a href="https://x.com/Arjun06061" target="_blank" rel="noopener noreferrer" className="text-emerald-400 hover:underline">𝕏 Twitter</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

